lib/WebSocket.js, test/WebSocket.test.js
Sorry, I found a bug which happens when setting the `compress` option `true` explicitly.
```js
ws.send(data, { compress: true });
Uncaught TypeError: Cannot call method 'compress' of undefined
```
=> Fix error when compress option is true and perMessageDeflate is disabled

src/bufferutil.cc, src/validation.cc
ws passes an 'extern "C"' function to the NODE_MODULE macro.
The API docs at http://nodejs.org/api/addons.html DO NOT use 'extern
"C"'.
Removing 'extern "C"' causes the module to work properly on my system
(Ubuntu 14.04, 64bit, node v0.10.25).
Fixes #434
=> Fix module registration

src/bufferutil.cc, src/validation.cc
Do use 'extern "C"' for the module's init function if nodejs version is less than 0.10.0.
This fixes the travis test for nodejs v0.8.
###########################
Apologies for breaking the travis-ci test for nodejs v0.8 with my last pull request.
This one conditionally keeps the 'extern "C"' for older node releases.
Tests for both versions are green https://travis-ci.org/pjump/ws
=> Make it work on nodejs v0.8 too

lib/WebSocket.js, test/WebSocket.test.js
When the WebSocket's HTTP request gets either an error or a response event, the cleanupWebsocketResources is called on this, which is the HTTP request, rather than self which prevents a clean close.
=> Fix for cleanupWebsocketResources using the wrong 'this'

lib/WebSocket.js, test/WebSocket.test.js
This fixes the long-running issue https://github.com/websockets/ws/pull/272 by removing the Origin header by default.
The default value "host:port" was not syntactically valid according to RFCs, which caused (some) servers to reject such connections. According to the WebSocket RFC 6455 it should be one of 1) missing 2) "null" 3) "scheme://host:port" (defined by the Origin RFC 6454).
Semantically, an origin header is not required for non-browser clients, and if present it should describe the source of the resource which caused this request. If the caller of ws has such origin, it can set it in the options (test case provided).
=> adhere to RFC by removing default Origin header

lib/Sender.js, test/WebSocket.test.js
Related: https://github.com/websockets/ws/issues/523
=> Fix for sending typed arrays or ArrayBuffer when perMessageDeflate is enabled

lib/WebSocket.js, test/WebSocket.test.js
url.parse returns an object with the port as a string. This allows interoperablity with servers with a more strict interpretation of https://tools.ietf.org/html/rfc6455#page-17
The way the RFC is worded could be interpreted to mean the port on the Host header is optional except if it is a default port, in which case it should not be included.
This will change will leave the port off of the Host header if it is a default port, even if it was explicitly specified.
=> fix Host header port inequality check

lib/WebSocket.js, test/WebSocket.test.js
Fixes #511.
The `type` property of the event should refer to the event type that is being fired. Unfortunately `type` for message events was being used to pass Binary/Text which was not only non-standard but broken applications that relied on the browser behavior.
This PR fixes events to have the proper type, and adds a non-standard `binary` property that has the value of `flags.binary`. If people were relying on `event.type === 'Binary'` or `event.type === 'Text'`, then this is a breaking change.
=> Make websocket events be in line with browser

lib/WebSocketServer.js, test/WebSocketServer.test.js
This patch will fix the status coded returned for non-Upgrade requests, changing it from `200` to `426`.
See #472.
=> Return 426 for non-Upgrade requests

lib/WebSocket.js
I think that the `realHandler` function was designed to push data efficiently to the receiver after the first chunk of data, but it seems that it never worked as intended.
If you look at the commit where it was intruduced (1faa9525) you'll see that the socket data handler is set to be `dataHandler` which points to `firstHandler` when the listener is registered. When `firstHandler` is invoked the value of `dataHandler` is changed to `realHandler`, but this doesn't replace the listener which will keep to be `firstHandler`.
With this patch the listener is correclty switched.
P.S. In #212 `socket.on('data', dataHandler);` was moved at the end of the function to ensure that the `readyState` was set to `WebSocket.OPEN` before receiving any data, but this is not needed because a net stream data …
=> Correctly switch the socket data handler

lib/BufferPool.js, lib/PerMessageDeflate.js, lib/Receiver.hixie.js, lib/Receiver.js, lib/Sender.hixie.js, lib/Sender.js, lib/WebSocket.js, lib/WebSocketServer.js, test/BufferPool.test.js, test/PerMessageDeflate.test.js, test/Receiver.hixie.test.js, test/Receiver.test.js, test/Sender.hixie.test.js, test/Sender.test.js, test/WebSocket.test.js, test/WebSocketServer.test.js
I had the strangest bug where it would throw an error instead of emitting `connected`. Turns out that I wasn't using the `new` keyword when creating my `WebSocketServer`. This pull requests throws an error when creating the instance as to alert the user of the misstake as soon as possible. It follows closely how it's done in [ES6 (9.2.2 - [[call]])](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-function-objects-call-thisargument-argumentslist) with the new `class` keyword.
I have added new tests and all test passes.
=> Throw TypeError when class constructor called without new

lib/WebSocketServer.js
HTTP server sets `allowHalfOpen` to true, but we want that to be false in websockets otherwise we get lots of connections with `CLOSE_WAIT` status
=> Allow pending CLOSE_WAIT connections to close

.travis.yml
Adds io.js to the Travis tests. Also removes tests for minor versions because versions like io.js 1.8.x and 2.5.x weren't being tested.
Also adds `sudo: false` which runs the tests on Travis' docker infrastructure, which launches tests more quickly: http://docs.travis-ci.com/user/migrating-from-legacy/
=> Add io.js 3 to the testing matrix and test only major versions

.travis.yml
Building the native modules (utf-8-validate and bufferutil) with io.js 3.0 requires C++11. Travis uses an ancient version of gcc (4.6) which doesn't support C++11, so this commit tells Travis to install gcc/g++ 4.9 and use it with node-gyp.
=> Update gcc/g++ during Travis tests so that we get C++11

lib/WebSocket.js, lib/WebSocketServer.js, test/WebSocket.test.js, test/WebSocketServer.test.js
When `WebSocket` and `WebSocketServer` are invoked as a function (i.e. without the `new` keyword), instead of throwing an error (change introduced in PR https://github.com/websockets/ws/pull/468/), it should create and return a new instance.
In addition to this I also removed the related test cases.
=> Return new instance if new keyword is missing.

lib/PerMessageDeflate.js, lib/WebSocket.js
Hi! It seemed the memory allocated by perMessageDeflate is not properly freed, thus causing memory leaks when this feature is enabled (as reported here https://github.com/websockets/ws/issues/497)
As documented [here](http://www.zlib.net/manual.html) and implemented [here](https://github.com/nodejs/node/blob/master/src/node_zlib.cc#L79), calling `.close()` on DeflateRaw and InflateRaw objects should (at least partially) fix these leaks.
Related: https://github.com/socketio/socket.io/issues/2251
*(please tell me this is it)*
=> Release memory used by PerMessageDeflate extension

lib/WebSocketServer.js
This will make close() compatible with Promise libraries like bluebird by providing a callback when its finished.
Note that this version only works correctly for the cases where the http server was **not** internally created.
If you like, you can support the other case as well (would need to pass a callback to `this._closeServer()`).
=> Callback for close() on WebSocketServer

lib/Receiver.js
Fix https://github.com/websockets/ws/issues/594
This PR forces to create a new buffer on each packet process so that buffers would not be affected each other.
As far as I benchmarked this by `bench/speed.js`, there is no performance problem.
=> Fix error when permessage-deflate is enabled

lib/PerMessageDeflate.js
This should fix https://github.com/websockets/ws/issues/628, which I think is caused by:
- deflate is closed
- `deflate.write()` then triggers an 'error' event
- `cleanup()` removes the listener attached to the 'error' event
- `deflate.flush()` triggers the uncaught error 'zlib binding closed' 
Does this make any sense?
=> Fix "zlib binding closed" errors

lib/Receiver.js
`Buffer` inherits from `Uint8Arry` so the constructor needs to be
called with integers and mustn't be called with floats.
This patch ensures that the result of the the calculation
in the `shrinkStrategy` in `Receiver` returns an integer.
The reason why this has not been a problem up to now is that
a there is a [V8 Bug](https://code.google.com/p/v8/issues/detail?id=4552)
that the [spec](http://tc39.github.io/ecma262/#sec-typedarray-length)
is not adhered in this case.
This is a blocking issue for [Karma](https://github.com/karma-runner/karma/issues/1768)
as the upgrade to [core-js@2.0.0](https://github.com/zloirock/core-js)
now enforces this error.
=> fix: shrinkStrategy should always return an integer

package.json
I'm attempting to use [nexe](https://github.com/jaredallard/nexe) to build a node application. Lack of the `main` field was causing the bundle to fail. Adding it appears to fix the issue.
=> [pkg]: add `main` field to package.json

SECURITY.md, lib/PerMessageDeflate.js, lib/Receiver.js, lib/WebSocket.js, lib/WebSocketServer.js, test/Receiver.test.js, test/WebSocketServer.test.js
Limit the amount of data that can be sent to a websocketserver from a
hybi client.
Raise a 1009 - message too big error.
Tests included.
Borrows some ideas and code from https://github.com/websockets/ws/pull/574/files
=> Add maxpayload limit to hybi clients

lib/WebSocket.js, test/WebSocket.test.js
The W3C WebSocket interface includes a binaryType attributes for a
socket and a corresponding BinaryType { 'blob', 'arraybuffer' } enum.
This enables support for the 'arraybuffer' BinaryType, but avoiding
changing the existing behaviour the default binaryType is set as
'nodebuffer'. The 'blob' type is left unsupported.
This improves ws compatibility with some existing W3C WebSocket based
client code.
Fixes: #441
=> lib/WebSocket.js: expose binaryType property

lib/Receiver.hixie.js, lib/Receiver.js, test/Receiver.test.js, test/WebSocketServer.test.js
Fix for #680 cc @rkaw92, test added.
=> Fix for #680 (https://github.com/websockets/ws/issues/680)

lib/WebSocket.js, test/WebSocket.test.js
Hi,
It would be foolish of me to think that the following statement in [WebSocket.js](https://github.com/websockets/ws/blob/master/lib/WebSocket.js) existed for no reason:
```var emitClose = this.readyState !== WebSocket.CONNECTING;```
But this is preventing the ```close``` event from being emitted when the initial HTTP handshake fails. It also creates a discrepancy in behavior between the browser vs a node.js app.
According to [WHATWG](https://html.spec.whatwg.org/multipage/comms.html#the-websocket-interface) and [W3C](https://www.w3.org/TR/websockets/):
> If the establish a WebSocket connection algorithm fails, it triggers the fail the WebSocket connection algorithm, which then invokes the close the WebSocket connection algorithm, which then establishes that the WebSocket connection is …
=> Emit both an error and close event when connection establishment fails

lib/WebSocketServer.js, test/WebSocketServer.test.js
This gave me quite a headache to debug in a test suite where I had an express server running on the same port as the `WebSocketServer`. I had no need to close the express server, but I needed to close the `WebSocketServer` to do some clean-up between tests. And I had weird error messages popping-up at second test. Turns-out all event handlers (e.g. `"upgrade"`) where still called on the old `WebSocketServer` even though I had closed it after end of first test.
=> Clean event handlers on WebSocketServer's internal http server when closing

lib/Sender.js
This creates a new masking key for each frame.
Ref: #634
=> Sender: Don't reuse masking key

lib/WebSocket.js
The `typeof options.value.perMessageDeflate !== true` always `false`.
=> fix PerMessageDeflate options pass issue

lib/WebSocket.js, lib/WebSocketServer.js, test/testserver.js
Solves https://github.com/websockets/ws/issues/716, which originated in Node v6 due to [this breaking change](https://github.com/nodejs/node/pull/5522#discussion_r54774150).
=> specify data encoding type 'binary' at hash#update

lib/Receiver.js
The `messageBuffer` property is not used anywhere, so this patch removes the whole assignment.
=> Remove unnecessary assignment

lib/Receiver.hixie.js, lib/Receiver.js, lib/Sender.hixie.js, lib/WebSocket.js, test/WebSocket.test.js
This patch makes sure that the `error` listener of the `WebSocket` object always receives an error. All errors now have a meaningful stack trace.
=> Make sure that no string is emitted as an error

bench/sender.benchmark.js, bench/util.js, lib/Sender.js, lib/WebSocket.js
The V8 engine optimizes code on a per-function basis. But it can't optimize functions that have a `try {} catch {}` block in them. Because of this, `frameAndSend()` was not getting optimized. And I don't know about you, but I'd say that's a pretty important function for optimization.
To fix this, I moved the `try {} catch {}` block into a separate function.
Also, when converting from ArrayBuffers/TypedArrays to Buffers, the data was being copied in memory, which has a speed of _O(n)_. With this pull request, converting between the two will no longer copy the memory, which is much faster; _O(1)_.
Also, I renamed the function `getArrayBuffer ` to `getBufferFromNative ` to better describe what it actually does.
=> increased performance of frameAndSend

lib/WebSocket.js
This allows people to use the `checkServerIdentity` option of the underlying https agent.
=> Added checkServerIdentity option to WebSocket

lib/Receiver.js
Avoiding a copy means improved performance, especially with large messages.
=> Avoid using Buffer.concat() on single part messages and provide length otherwise

lib/Sender.js, test/Sender.test.js
If a message has many messageHandlers it can trigger a stack overflow as it recursively calls flush on each one. This ensures that the stack is cleared before each recursive flush is called. 
Fixes #809
=> Fix stack overflow crash

bench/speed.js
- Set the `maxPayload` option to `Infinity`.
- Use the correct event (`exit`) to detect when the worker in the cluster dies.
Fixes #833.
=> Fix speed benchmark

test/WebSocket.test.js
bufferSize was removed from node in 0.9.12 so this test was ineffective
=> Replace bufferSize with highWatermark.

bench/parser.benchmark.js, bench/sender.benchmark.js, bench/util.js, package.json
- Avoid using global variables.
- Remove unused functions from `bench/util.js`.
- Fix issues with strict mode and global variables.
=> Fix and clean up parser and sender benchmarks

lib/Receiver.js
- First commit removes all occurrences of `Function.prototype.call()` in favor of direct function invocation.
- Second commit applies some style changes.
=> Avoid using `Function.prototype.call()`

.eslintrc, package.json
- Use mocha env in eslint config instead of adding each mocha global manually.
- Update eslint to version 3.7.x.
=> Add mocha env to eslint config

lib/Sender.js
If `data` is falsy, the function exits [early](https://github.com/websockets/ws/blob/cad49db8a825d99c68a9330be86e0aa590ecf53e/lib/Sender.js#L129-L134).
=> Remove redundant check

lib/WebSocketServer.js, test/WebSocketServer.test.js
I think it makes sense to use a `Set` instead of an `Array` to track clients.
The main advantage is that `Set.prototype.delete()` complexity is sublinear per spec.
=> Use a set instead of an array to track clients

lib/Sender.js, lib/WebSocket.js
The only event emitted by `Sender` is `error` so I think it makes sense to not make it inherit from `EventEmitter` and only use an `onerror` function instead.
This is also consistent with the `Receiver` class.
=> Remove Sender inheritance from EventEmitter

lib/WebSocketServer.js, test/WebSocket.test.js, test/WebSocketServer.test.js
When a client visits a server with a wrong path, the connection should be rejected.
=> Issue path validation

lib/Receiver.js
We don't need this at all - we can pull from the receiver's buffer when we are ready for the next frame.
=> Remove messageHandler mechanism in Receiver

lib/Receiver.js, test/Receiver.test.js
- cc4bd20
Right now the `currentPayloadLength` counter is reset every time `endPacket` is called. This doesn't work as expected for fragmented messages where `currentPayloadLength` should be the sum of the bytes of each incoming fragment. cc4bd20 fixes the issue by resetting `currentPayloadLength` only on the final frame.
- 9a2a3a1
`expectData` sets a value to those properties in its body so there is no reason to do it twice.
- b2aae29
The `fragmentedOperation` flag seems to be unnecessary. It is only assigned and never checked.
=> Reset `currentPayloadLength` only on final frame

lib/Sender.js
6b3904b introduced a [bug](https://github.com/websockets/ws/commit/6b3904b42dbd48aed2e0d8d599787cca04f05384#commitcomment-19666069) where a buffer sent with a ping/pong message is first converted to a string and then back to a buffer, changing the original data.
This patch should fix the issue.
=> Prevent data corruption when sending ping/pong messages

bench/parser.benchmark.js, lib/Receiver.js, test/Receiver.test.js
This is a rewrite of the parser. The main advantages are:
- No callbacks.
- No duplicated code.
- Faster for small frames.
- Easier to read and understand (I hope).
- Better error messages.
**Benchmarks**
before (master branch with the same changes applied to `parser.benchmark.js`)
```
ping message x 635,655 ops/sec ±1.15% (84 runs sampled)
ping with no data x 3,950,735 ops/sec ±1.60% (84 runs sampled)
close message x 3,851,346 ops/sec ±1.37% (85 runs sampled)
masked text message (20 bytes) x 428,833 ops/sec ±1.54% (85 runs sampled)
binary data (125 bytes) x 536,784 ops/sec ±1.56% (82 runs sampled)
binary data (65535 bytes) x 48,578 ops/sec ±1.07% (84 runs sampled)
binary data (200 KiB) x 6,213 ops/sec ±0.83% (86 runs sampled)
binary data (1 MiB) x 1,238 ops/sec ±0.72% (85 runs sampled) …
```
=> Rewrite the parser

bench/sender.benchmark.js, lib/Sender.js, test/Sender.test.js
This adds an additional argument to `Sender.prototype.frameAndSend()` to specify if `data` can be masked in place.
This is useful for example when the data to send is a string or when data is compressed. In these cases it is safe to mask in place as the original data is left untouched.
Buffers whose size is less than 1 KiB are still copied unconditionally to reduce system calls.
=> Avoid copying buffers when possible

lib/WebSocketServer.js, test/WebSocketServer.test.js
The `_webSocketPaths` object is added to the underlying HTTP sever of a `WebSocketServer` when the `path` option is specified. It is used to store the path of each `WebSocketServer` using the same underlying HTTP server in order to avoid path conflicts.
```js
const server = http.createServer();
const wss1 = new WebSocket.Server({ server, path: '/foo' });
const wss2 = new WebSocket.Server({ server, path: '/bar' });
```
This allows to use multiple WebSocket severs (one per path) and only one shared HTTP server.
The problem here is that each `WebSocketServer` adds a new listener for the `upgrade` event on the HTTP server and when that event is emitted, [`handleUpgrade`](https://github.com/websockets/ws/blob/ebf86b58f1fb1e96ab96ebf95782bad7bc5ab8ca/lib/WebSocketServer.js#L164-L180) is called …
=> Remove path registry

lib/PerMessageDeflate.js, test/PerMessageDeflate.test.js, test/Sender.test.js
I started wondering why very similar packets didn't compress better. Turns out the Node.js API for `zlib` is a tad bit misleading: the kind of flush needs to be specified when calling `flush` even if it's been specified in the options (see https://nodejs.org/api/zlib.html#zlib_zlib_flush_kind_callback). 
This pull requests calls `flush` with the correct level and adds a test that checks that the compression actually makes similar packets smaller.
Note: I gave this only a very preliminary testing. Please do testing across more browsers before even considering merging.
=> Permessage-deflate calls zlib flush with wrong flush level

lib/WebSocketServer.js
Right now the close callback is invoked immediately but it should be called when the HTTP server emits the 'close' event.
=> Invoke the close callback when the close event is emitted

doc/ws.md, lib/WebSocketServer.js, test/WebSocketServer.test.js
Right now `handleProtocols` takes a callback which must be called **synchronously** by the developer with two arguments: the outcome of the operation and the selected protocol.
I think it makes sense to remove the callback argument and use the returned value instead.
=> Remove callback from `handleProtocols`

test/autobahn-server.js, test/autobahn.js
The test files used an older API for `message` events.
=> Fix Autobahn tests

lib/Sender.js
This renames `Sender#messageHandlerCallback` to `Sender#continue` and `Sender#flush` to `Sender#dequeue`.
I think these new names better reflect what the methods do. Everything is private so there shouldn't problems. I've opened this PR to see if other collaborators agree on the names.
=> Rename some methods of the `Sender` class

lib/EventTarget.js, lib/WebSocket.js
This patch:
- Moves the `EventTarget` methods (`addEventListener` and `removeEventListener`) and classes (`MessageEvent`, `CloseEvent` and `OpenEvent`) to the `EventTarget.js` file.
- Cleans up a bit `WebSocket.js` by adding JSDoc and modernizing the code of some methods/attributes.
=> Move the EventTarget methods to lib/EventTarget.js

doc/ws.md, lib/WebSocket.js, test/WebSocket.test.js
Hixie-76 is no longer supported so this non-standard attribute can be removed as binary messages are always supported.
=> Remove `supports` attribute

lib/Sender.js, test/Sender.test.js
Currently the [callback](https://github.com/websockets/ws/blob/199c248a4a65d175fdcb351ff1d29c87debaf855/lib/Sender.js#L72) of `Sender.prototype.close()` is immediately invoked regardless of data being sent or not.
This patch forwards the callback of `Sender.prototype.close()` to `Sender.prototype.frameAndSend()` to actually call the callback when data is written out.
=> Call `Sender#close()` callback when data is written out

index.js
=> Remove `WebSocket.createServer()` and `WebSocket.connect()`

lib/WebSocket.js, test/WebSocket.test.js
- Refactor `WebSocket` to use the ES6 class syntax.
- Move `cleanupWebsocketResources` and `establishConnection` to `WebSocket.prototype`.
- Rename `establishConnection` to `setSocket` and `cleanupWebsocketResources` to `finalize`.
- Keep `initAsServerClient` and `initAsClient` as completely private API.
=> Refactor `WebSocket` to use class syntax

lib/WebSocket.js, test/WebSocket.test.js
The `host` header is already correctly built when the `http.ClientRequest` is created.
If the port number is the default one it is not added to the `host` header field value.
=> Remove unnecessary `buildHostHeader` function

bench/sender.benchmark.js, lib/Sender.js, test/Sender.test.js
This updates the signature of the `frameAndSend` method to make it accept an options object.
This should make it easier to add more options in future without having to add more arguments and remember their position.
=> Change `Sender.prototype.frameAndSend()` signature

lib/Receiver.js, lib/WebSocket.js, test/Receiver.test.js, test/testserver.js
This merges `receiver.onbinary` and `receiver.ontext` into `receiver.onmessage`.
I think thank using 2 different handlers is pointless.
This is tagged as "major" because it changes the `Receiver` interface but I don't think many people are  using the `Receiver` and `Sender` classes directly. Their interface is not documented and imo they should be private and not used directly. Unfortunately they are exposed as static properties of the `WebSocket` class.
I was also thinking that maybe it makes sense to emit to the `WebSocket` instance directly instead of using these wrapper [functions](https://github.com/websockets/ws/blob/fc956f8071e3930de432676ea2ea9cc075ee9fde/lib/WebSocket.js#L139).
For example we could make the `Receiver` constructor accept a `WebSocket` instance, the one the …
=> Use the same handler for binary and text messages

lib/WebSocket.js, test/WebSocket.test.js
Currently the close handshake works like this when initiated from the server:
```
SERVER                                 CLIENT
+--------------------+
|ws.close()          |
|readyState = CLOSING|
+--------------------+
|            +-----------+
+----------->|close frame|-------------+
+-----------+             v
+--------------------+
|closeReceived = true|
|ws.close()          |
|readyState = CLOSING|
+--------------------+
+-----------+             |
+------------|close frame|<------------+
v            +-----------+
+--------------------+
|closeReceived = true|
|ws.close()          |
|ws.terminate()      |
|socket.end()        |
+--------------------+
|              +-------+
+------------->|TCP FIN|---------------+
+-------+               v
+-------------------+
|readyState = …
```
=> Simplify closing handshake

lib/Receiver.js, lib/WebSocket.js, test/Receiver.test.js, test/WebSocket.test.js
This makes `Receiver.prototype.cleanup()` accept an optional callback which is called when all buffered data is consumed or an error occurs.
Using this callback we can handle cases where the parser is decompressing data and the other peer closes the underlying TCP connection. Previously when this happened the buffered data was simply discarded. Now all data should be handled correctly.
Fixes #799 and #923.
This is based and supersedes #840.
@websockets/admin this really needs to be reviewed carefully so when you have time please take a look.
=> Consume all data before emitting the `close` event

doc/ws.md, lib/Sender.js, lib/WebSocket.js, test/Sender.test.js, test/WebSocket.test.js
With this change `Websocket.prototype.ping()` and `Websocket.prototype.pong()` take a boolean as second argument instead of an options object.
Ping/Pong messages can't be compressed or fragmented and are always binary, so I think it doesn't make sense to use an options object as the only thing which can be (arguably) configured is whether or not to mask data.
=> Use a boolean instead of an options object

lib/WebSocket.js, lib/WebSocketServer.js
Hi, 
I discovered a leakage in WebSocket.clients when using callbacks like so for WebSocket
```
ws.onclose = function close(evt) {
..
}
```
In the code I discovered that on connection on the server side a callback is registered to remove the peer from the ```WebSocket.clients``` Set
Unfortunately this hidden callback is removed when using  `ws.onclose = function `  style.
Since this is a cleanup operation, (after closure of socket) I changed the 'hidden' emit event name to "cleanup".
this will prevent the hidden callback removal when using  `ws.onclose == function` style callback
(Look at how onclose property is defined, in removes all event handlers , so also any hidden "close" event handlers)
=> WebSocket object leakage in WebSocketServer.clients when using WebSocket.onclose = function(..){..}

lib/WebSocket.js, test/WebSocket.test.js, test/WebSocketServer.test.js
Currently `WebSocket.prototype.close()` only sets the `readyState` to [`CLOSED`](https://github.com/websockets/ws/blob/8aa65e2f4da33083d1c20e46240aacc4fe40822c/lib/WebSocket.js#L267) if called before receiving a handshake response. Then the connection is eventually closed when the response is [received](https://github.com/websockets/ws/blob/8aa65e2f4da33083d1c20e46240aacc4fe40822c/lib/WebSocket.js#L633-L639).
This is wrong as the `connection` event is still emitted on the server.
This patch aborts the client request if `WebSocket.prototype.close()` is called before receiving a handshake response.
Fixes #388
=> Abort the request if `close` is called while connecting

doc/ws.md, lib/WebSocket.js, test/WebSocket.test.js
`http.request` accepts a `family` option to specify the IP address family to use when resolving the server hostname. Seems pretty reasonable to accept this from the WebSocket side and forward it over to the `http` request call.
Specifically, this is useful for Facebook since we have IPv6 only development servers with IPv4 proxies (in which case we need websockets to connect to the IPv6 address)
=> Accept hostname lookup `family` option when creating WebSockets

lib/WebSocket.js
This avoids mutating the passed in arguments.
The current behaviour breaks sending if you use the same options object for multiple send() calls. I don't know if anyone relies on the arguments being mutated or in being able to pass in undefined explicitly.
=> Use Object.assign() for send() options

lib/WebSocket.js, test/WebSocket.test.js
This prevents `WebSocket.prototype.close()` from triggering an infinite loop if called from an error listener while connecting.
Refs: https://github.com/websockets/ws/pull/956#issuecomment-272585388.
=> Prevent `WebSocket#close()` from triggering an infinite loop

README.md
This adds a WebSocket compression section to specify that permessage-deflate should be used only when really necessary.
=> Add WebSocket compression section

README.md
This removes a link to a very old blog post (2011).
=> Remove outdated link and rephrase sentence accordingly

lib/Sender.js, lib/WebSocket.js, test/Sender.test.js, test/WebSocket.test.js
This makes the `bufferedAmount` getter take into account the data queued in the sender.
Fixes #970.
cc: @alexions
=> Take into account the data queued in the sender

bench/parser.benchmark.js, lib/Receiver.js, test/Receiver.test.js
This makes the parser work with buffers containing thousands of frames.
Fixes #990.
cc: @Nibbler999
=> Prevent the parser from triggering a stack overflow

lib/Sender.js
This is a backport of https://github.com/websockets/ws/pull/832/files to v1.x, so that projects that still need to support Node < 4 can get the security patch.
=> Security: Use crypto.randomBytes, not Math.random

lib/PerMessageDeflate.js, lib/Sender.js, test/WebSocket.test.js
When permessage-deflate is enabled the outbound throughput performance is throttled by `process.nextTick()`. If the are `n` messages in the queue, it will take `n` ticks before all messages are dispatched even when compression is skipped.
This patch prevents `process.nextTick()` from being used by slightly changing the handling logic of the queued messages.
=> Write to the socket as soon as possible

bench/sender.benchmark.js, lib/Sender.js, test/Sender.test.js
This transforms `Sender.prototype.frameAndSend()` into a static method (`Sender.frame()`) which can be used to frame data.
Having a function which returns a frame gives developers more fine grained control and allows them to optimize certain operations like a server broadcast where the same frame should be sent to all clients.
=> Make `Sender#frameAndSend()` a static method

lib/BufferUtil.js, lib/PerMessageDeflate.js, lib/Receiver.js
This patch adds a new function to merge an array of buffers and replaces all occurrences of `Buffer.concat()` with it.
The reason for this change is that `Buffer.concat()` [checks](https://github.com/nodejs/node/blob/87a039d721b7e9fd73365774ac3e27166e4e1f6e/lib/buffer.js#L333) that every element in the array is an instance of `Buffer` and this makes it perform worse.
=> Avoid using `Buffer.concat()`

lib/WebSocket.js, test/WebSocket.test.js
I was playing with making a websocket server and connecting to it using `wscat`, so I did: `wscat -c ws://0.0.0.0 -p 3000` and I got:
> Error: unsupported protocol version
That made me think my webserver was wrong when in fact `-p` is the protocol version and not the port, e.g. `wscat -c ws://0.0.0.0:3000` works.
So I improved the error message:
> Error: unsupported protocol version 3000 (supported versions: 8, 13)
=> Error message for unsupported protcol version

doc/ws.md, lib/WebSocket.js
Currently `WebSocket.prototype.terminate()` only sends a FIN packet to the other peer. If `allowHalfOpen` is `true` and the other peer does not call `socket.end()` the connection will only be closed when the timeout [expires](https://github.com/websockets/ws/blob/4a605b9853a36ce53332f3cad87127b47d4d1030/lib/WebSocket.js#L403).
This patch makes `WebSocket.prototype.terminate()` use `socket.destroy()` so the connection is closed immediately even if the other peer fails to work properly.
Fixes #891.
=> Make `WebSocket#terminate()` destroy the socket

.travis.yml, appveyor.yml, bench/parser.benchmark.js, bench/speed.js, lib/BufferUtil.js, lib/Constants.js, lib/PerMessageDeflate.js, lib/Receiver.js, lib/Sender.js, lib/WebSocketServer.js, package.json, test/PerMessageDeflate.test.js, test/Receiver.test.js, test/Sender.test.js, test/Validation.test.js, test/WebSocket.test.js, test/WebSocketServer.test.js, test/hybi-util.js
It seems that in some cases upgrading to v2 is not possible due to the minimum required Node.js version (v4.5.0). See for example the discussions in https://github.com/maxogden/websocket-stream/pull/106 and https://github.com/maxogden/websocket-stream/issues/108.
This patch makes `ws@2` works with all v4 versions.
It is tested in v4.1.0 because the previous release v4.0.0 has known bugs and tests fail.
=> Add support for Node.js 4.1.0 - 4.4.7

doc/ws.md, lib/WebSocketServer.js, test/WebSocketServer.test.js
This adds the upgrade request to the argument list when emitting the `headers` event and also pass it as second argument to the `handleProtocols()` hook.
Closes #787
Fixes #783
Fixes #683
Fixes #525
=> Make all hooks have access to the upgrade request

README.md
This addition is to make clearer to confused users that they should be using the native WebSocket on the browser.
=> Added a note about browser usage in the Readme

lib/Sender.js
`Sender.frame()` is deoptimized on both Node.js 7.9.0 (V8 5.5) and Node.js master (V8 5.7):
```
[deoptimizing (DEOPT eager): begin 0x18d18fffc341 <JS Function frame (SharedFunctionInfo 0x363deeaa5fd9)> (opt #47) @6, FP to SP delta: 152, caller sp: 0x7fff5fbf5fb8]
;;; deoptimize at 1690: wrong map
reading input frame frame => node=30, args=3, height=7; inputs:
0: 0x18d18fffc341 ; [fp - 16] 0x18d18fffc341 <JS Function frame (SharedFunctionInfo 0x363deeaa5fd9)>
1: 0x2a9eba4c7501 ; [fp + 32] 0x2a9eba4c7501 <JS Function Sender (SharedFunctionInfo 0x363deeaa5f11)>
2: 0x3f42cc2561c9 ; rbx 0x3f42cc2561c9 <an Uint8Array with map 0x271baad2c9f1>
3: 0x3f42cc256451 ; r8 0x3f42cc256451 <an Object with map 0x271baad5ba11>
4: 0x18d18fffaa19 ; [fp - 24] 0x18d18fffaa19 <FixedArray[5]>
5: 0x29b138d02351 ; …
```
=> Prevent `Sender.frame()` from being deoptimized

doc/ws.md, lib/WebSocket.js, test/WebSocket.test.js
Adds headers event.
The only thing that's slightly weird about this is that WebSocketServer emits an array of headers, and this emits an object of headers.  We could emit the [rawHeaders](https://nodejs.org/api/http.html#http_message_rawheaders) here, and then they'd match... But most people probably want the headers object anyways.
=> #1081: Add headers event to WebSocket.

lib/WebSocketServer.js, test/WebSocketServer.test.js
The canonical `connection` event is sufficient as the URL is exposed via `ws.upgradeReq.url`.
=> Remove unnecessary events

README.md, bench/speed.js, doc/ws.md, examples/fileapi/server.js, lib/EventTarget.js, lib/Receiver.js, lib/WebSocket.js, test/WebSocket.test.js, test/WebSocketServer.test.js
The `flags` object specifies whether the received data is binary or not and whether it was masked or not. This object is actually redundant and therefore removed in this commit as the spec requires client-sent frames to be masked and server-sent frame to be unmasked.
The `typeof` operator can be used to check whether the received data is binary or not.
=> Remove the `flags` argument

README.md, doc/ws.md, examples/express-session-parse/index.js, lib/WebSocket.js, lib/WebSocketServer.js, test/WebSocket.test.js, test/WebSocketServer.test.js
This removes the `upgradeReq` property from the `WebSocket` object. The `http.IncomingMessage` object is instead passed as the second argument to the `connection` event.
In this way most of the memory retained by the `http.IncomingMessage` object can be GC'ed reducing memory usage by ~20%.
Developers can save only the required info or the whole `http.IncomingMessage` object, if they have to, when the event is emitted.
See discussion in #1099.
=> Remove the `upgradeReq` property

lib/PerMessageDeflate.js, lib/Receiver.js, lib/Sender.js, lib/WebSocket.js, lib/WebSocketServer.js, test/Receiver.test.js, test/WebSocketServer.test.js
This patch prefixes all private properties with `_` in order to improve consistency in our codebase.
I wanted to use symbols for private properties but it makes testing and debugging harder. We are also still supporting Node.js 4 and symbols have a significant performance impact there.
=> Prefix all private properties

README.md, doc/ws.md, lib/WebSocketServer.js, test/WebSocket.test.js, test/WebSocketServer.test.js
This patch disables permessage-deflate by default on the server.
=> Have permessage-deflate disabled by default

README.md, bench/speed.js, doc/ws.md, examples/express-session-parse/index.js, examples/fileapi/server.js, lib/EventTarget.js, lib/PerMessageDeflate.js, lib/Receiver.js, lib/Sender.js, lib/WebSocket.js, lib/WebSocketServer.js, test/Receiver.test.js, test/WebSocket.test.js, test/WebSocketServer.test.js
This PR contains the following changes:
- Removes the `upgradeReq` property from the `WebSocket` object and instead pass the `http.IncomingMessage` as the second argument to the `'connection'` event. This reduces memory usage by ~20%.
- Removes the `flags` argument from the `'message'`, `'ping'`, and `'pong'` events. This object is not needed.
- Disables permessage-deflate by default on the server.
- Prefixes all private properties.
Closes #1097.
=> Enhancements

doc/ws.md
Hi! I spotted a few typos when reading through the documentation
=> Fix typos in API docs

README.md
Hi there,
Like the subject says, this PR just fixes two minor typos in `README.md`.
Thanks for `ws`!
=> Fix "unware" and "reponse" typos in README.md

doc/ws.md, lib/WebSocket.js, test/WebSocket.test.js
Hi,
I have the need to control the connection timeout when initialising the connection,
I did my best to fall into your coding style and added the option in the documentation and added a unit test.
Hoping you will find this to your liking,
Let me know if there's anything I need to change, thanks!
=> allow client to specify handshake request timeout

doc/ws.md, lib/PerMessageDeflate.js, test/PerMessageDeflate.test.js
This corresponds to the zlib level as described
in https://nodejs.org/api/zlib.html#zlib_class_zlib_deflateraw
This could be used, along with `threshold` to tune CPU usage and size. The default level in `zlib` is 6, which could be too high, but some users may find that 1 is worth the CPU savings for a quick pass.
For example, on some JSON sample data:
```
Running zlib.deflateRawSync for 1000 iterations.
Uncompressed Data Size: 137063 bytes
-----
Level 0: 550.879ms
Size: 137083 bytes
Level 1: 836.332ms
Size: 11379 bytes
Level 2: 825.474ms
Size: 10717 bytes
Level 3: 847.320ms
Size: 10397 bytes
Level 4: 1187.744ms
Size: 8388 bytes
Level 5: 1286.184ms
Size: 7761 bytes
Level 6: 1489.151ms
Size: 7372 bytes
Level 7: 1657.936ms
Size: 7301 bytes
Level 8: 1828.456ms
Size: 7187 bytes
Level 9: …
```
=> feat(perMessageDeflate): Allow 'level' option

doc/ws.md, lib/PerMessageDeflate.js, package.json
Ref: #1202 
Built on top of [async-limiter](https://github.com/STRML/async-limiter) which is only 1kB of dependency-free ES5.
=> [feature]: zlib deflate concurrency limit

lib/PerMessageDeflate.js, lib/Sender.js, lib/WebSocket.js
`zlib.DeflateRaw` emits an `'error'` event only when an attempt to use it is made after it has already been closed and this cannot happen in our case.
=> Remove unreachable code

lib/WebSocket.js
Support ecdhCurve option as discussed in https://github.com/websockets/ws/issues/1227
=> Add ecdhCurve option

lib/Extensions.js, lib/WebSocket.js, lib/WebSocketServer.js, test/Extensions.test.js, test/PerMessageDeflate.test.js, test/WebSocket.test.js
This rewrites the parser of the `Sec-WebSocket-Extensions` header to make it spec-compliant.
The implementation is not based on regular expressions to avoid possible ReDoS attacks. The added benefit is that it is faster than a [regex based parser](https://github.com/faye/websocket-extensions-node/blob/2af2c182515de125938430a82d1fe2c85a71c88b/lib/parser.js#L14-L51).
```
regex-parser x 154,349 ops/sec ±0.94% (84 runs sampled)
parser x 261,251 ops/sec ±0.92% (84 runs sampled)
```
There is probably also room for improvements and some duplicated code could be removed but I would prefer to leave this as a future exercise.
=> Rewrite the parser of the Sec-WebSocket-Extensions header

test/WebSocket.test.js
Seams a bit complicated but it's more consistent than simply skipping silently a test.
If the test is skipped it will be mentioned on the result (maybe we should raise an error during ci if a test is skipped) and the test will pass on more machine trying a list of potential alias for the loop-back.
with `const hostsCandidates = ['localhost'];`
```
WebSocket
options
- accepts the family option
```
with `const hostsCandidates = ['localhost', 'ip6-loopback'];`
```
WebSocket
options
✓ accepts the family option
```
with `const hostsCandidates = ['localhost', 'ip6-allnodes'];`
```
WebSocket
options
1) accepts the family option
0 passing (42ms)
1 failing
1) WebSocket
options
accepts the family option:
Error: connect ENETUNREACH ff02::1:39758 - Local (:::0)
```
=> [test] fix ipv6 test

doc/ws.md
Remove duplicate 'is' in doc.
before:
If it **is is** provided with a single argument then that is:
after:
If it **is** provided with a single argument then that is:
=> [doc] Remove duplicate 'is' in doc.

bench/parser.benchmark.js, bench/sender.benchmark.js, index.js, lib/buffer-util.js, lib/receiver.js, lib/sender.js, lib/validation.js, lib/websocket-server.js, lib/websocket.js
Some JS parsers seem to ignore it otherwise.
=> [minor] Move 'use strict' declarations on top of the file.

doc/ws.md, lib/websocket-server.js, test/websocket-server.test.js
Provide http server port directly from _server
Do I need to write test or anything else to complete this PR ?
Or better way to get port if I bind with 0
Thanks
=> Provide http server port directly from _server

README.md
`isomorphic-ws` is a tiny wrapper around `ws` (peer dependency) which returns `global.WebSocket` on the browser.
=> feat(README): add a link to isomorphic-ws

README.md, doc/ws.md, lib/permessage-deflate.js, test/permessage-deflate.test.js
It can be useful to adjust other options, and rather than support and document every single one, it is simpler to allow passing on an object wholesale.
`level` and `memLevel` are still supported but should be removed in 4.x.
I'm still working on solutions to https://github.com/nodejs/node/issues/8871 (tracked in https://github.com/nodejs/node/issues/15301). In the meantime, depending on workload, memory fragmentation can be greatly reduced by adjusting `chunkSize`.
=> [minor] add zlibOptions to perMessageDeflate init

.travis.yml, appveyor.yml, doc/ws.md, lib/constants.js, lib/permessage-deflate.js, lib/receiver.js, lib/websocket.js, test/receiver.test.js, test/websocket.test.js
This makes `Receiver` inherit from `stream.Writable`.
The main reason for this change is to have back-pressure properly handled when permessage-deflate is enabled.
There are no significant performance differences but memory usage is a lot higher. 100k connections use ~400 MB on master and ~600 MB with this patch.
I'm opening this PR to discuss whether or not this makes sense.
=> Make `Receiver` inherit from `stream.Writable`

doc/ws.md, lib/websocket-server.js, test/websocket-server.test.js, test/websocket.test.js
From https://tools.ietf.org/html/rfc6455#section-4.2.2
```
/subprotocol/
Either a single value representing the subprotocol the server
is ready to use or null.  The value chosen MUST be derived
from the client's handshake, specifically by selecting one of
the values from the |Sec-WebSocket-Protocol| field that the
server is willing to use for this connection (if any).  If the
client's handshake did not contain such a header field or if
the server does not agree to any of the client's requested
subprotocols, the only acceptable value is null.  The absence
of such a field is equivalent to the null value (meaning that
if the server does not wish to agree to one of the suggested
subprotocols, it MUST NOT send back a |Sec-WebSocket-Protocol|
header field in its response).  The empty string is …
```
=> Fix subprotocol handling

.travis.yml, appveyor.yml, bench/parser.benchmark.js, bench/speed.js, lib/buffer-util.js, lib/constants.js, lib/permessage-deflate.js, lib/receiver.js, lib/sender.js, lib/websocket-server.js, package.json, test/permessage-deflate.test.js, test/receiver.test.js, test/sender.test.js, test/websocket-server.test.js, test/websocket.test.js
Node.js 4.x will go EOL at the end of April and all versions below 4.8.7 have at least one security vulnerability. I see no reason to keep supporting versions in the range 4.0.0 - 4.4.7.
I actually want to drop support for all 4.x versions but maybe it's better to wait a little more.
=> Drop support for Node.js < 4.5.0

lib/receiver.js, lib/sender.js
Support for the `noAssert` argument dropped in the upcoming Node.js
10.x release. This removes it to make sure everything still works as
it should by already validating the input right away.
Refs: https://github.com/nodejs/node/pull/18395
=> [fix] remove buffer `noAssert` argument

doc/ws.md, lib/websocket.js, test/websocket.test.js
Currently it is only possible to use some of the tls options allowed in [https.request()](https://nodejs.org/api/https.html#https_https_request_options_callback). This add the ability to use all of them.
=> Allow all options accepted by `http{,s}.request()`

lib/buffer-util.js
Prefer the pure JS version of `mask()` and `unmask()` when working with very small buffers.
```
$ node mask.js 16
mask 16 bytes (JS) x 21,724,086 ops/sec ±0.77% (93 runs sampled)
mask 16 bytes (addon) x 6,730,729 ops/sec ±2.49% (94 runs sampled)
```
```
node unmask.js 16 
unmask 16 bytes (JS) x 21,601,809 ops/sec ±0.28% (88 runs sampled)
unmask 16 bytes (addon) x 9,842,054 ops/sec ±0.29% (89 runs sampled)
```
=> Use js version of `{un,}mask()` for very small frames

README.md, doc/ws.md
- Improve documentation for the `port`, `server`, and `noServer` options.
- Remove Express example in favour of a general external server integration example.
- Add "noServer" mode example.
=> Improve docs and examples

README.md
I spent 90-minutes trying to figure out why my `connection` handler `request` argument was undefined. I thought making the docs for the `noServer` configuration more idiomatic with the expected behavior of the `server` configuration might save others from frustration in the future.
=> [doc] "Multiple servers sharing...", add `request` to emit arguments

doc/ws.md, lib/websocket-server.js, test/websocket-server.test.js
Which is passed to abortHandshake().
Fixes: https://github.com/websockets/ws/issues/695
Fixes: https://github.com/websockets/ws/issues/728
=> verifyClient callback now accepts "headers" parameter

browser.js, package.json
=> throw a exception when be imported into Browser (#1344)

bench/speed.js, doc/ws.md, lib/websocket.js, test/websocket.test.js
I came across a situation where a websocket client instance needs to be protected against large messages. This pull request makes the option.maxPayload option available for client instances.
=> Added options.maxPayload for websocket clients

doc/ws.md, lib/websocket-server.js, test/websocket-server.test.js
=> Make `WebSocketServer#close()` emit the `'close'` event

lib/sender.js, lib/websocket.js, test/sender.test.js, test/websocket.test.js
Addresses #1226 - I agree with @lpinca 's approach in general.  This has been tested with the offending code listed in the issue and it correctly short circuits while still providing a relevant error to each pending request.  I've also added a unit test that fails without the added code as it tries to write/compress too much.
Not sure how I feel about having to add the extra `on: () => {}` to the Sender unit tests for the socket object, but these are mocks anyway.  Open to suggestions if this isn't preferred.
=> Do not waste time compressing when socket is closed

lib/sender.js, lib/websocket.js, test/sender.test.js, test/websocket.test.js
Do not invoke callbacks when clearing the send queue due to premature
socket closure.
Refs: https://github.com/websockets/ws/pull/1464#issuecomment-435578571
Fixes #1226
=> Ignore callbacks when clearing the send queue

lib/websocket.js, test/websocket.test.js
Prevent the default port from being added to the `Host` header when no
`Agent` is used.
Fixes #1505
=> Use the `defaultPort` option

doc/ws.md, lib/websocket.js, test/websocket.test.js
Known defects:
- The options object it rebuilt after every redirect. This could be optimized to only do it once and update only the options that need to be changed after every redirect.
- There might be issues if an agent is used and the protocol is changed from HTTPS to HTTP or vice versa since HTTPS and HTTP use different agents.
Fixes #812
=> Add ability to follow redirects

doc/ws.md
Thanks to The Nacho Man and his [nGitHubTOC](https://imthenachoman.github.io/nGitHubTOC/).
=> Add summary with links to the doc

README.md, lib/websocket.js, test/websocket.test.js
- If the `readyState` attribute is `CONNECTING`, throw an exception.
- If the `readyState` attribute is `CLOSING` or `CLOSED`
- Increase the `bufferedAmount` attribute by the length of the `data`
argument in bytes.
- If specified, call the `callback` function with an error.
Fixes #1515
=> Change `WebSocket#{p{i,o}ng,send}()` behavior

README.md
Hey!
In the "Multiple servers sharing a single HTTP/S server" usage example URL module is used but it's not included in the snippet. This PR is adding 
```javascript
const url = require('url');
```
line to make the snippet valid.
=> docs: Add missing dependency in code snippet

lib/event-target.js, lib/websocket.js, test/websocket.test.js
=> add stub dispatchEvent method to WebSocket (#1583)

lib/websocket.js, test/websocket.test.js
The option `servername` in [`tls.connect(options[, callback])`](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) is the name of the host being connected to, and must be a host name, and not an IP address. If the server is not a multi-homed server and I want to connect with the IP address it is not possible to disable sending the SNI extension by setting the servername to empty string `''`. This PR implements the defaulting of the `servername` in the same way as it is done in the [node](https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L161-L162). 
This PR is related to #1347 .
**Example**
In node v12 with the following code
```js
new WebSocket('wss://127.0.0.1', {
ca: fs.readFileSync('ssl/ca.pem'),
servername: '',
})
```
I get the deprecation warning …
=> Setting the servername to an empty string '' should disable sending the SNI extension.

README.md, doc/ws.md, index.js, lib/stream.js, test/create-websocket-stream.test.js
I'm not sure if it make sense to add this but reasons for doing it are:
- No additional dependencies.
- Functionality is strictly bound to the ws internals.
- Already existing modules are broken. The most popular, [websocket-stream](https://github.com/maxogden/websocket-stream)
- [Loses data](https://github.com/maxogden/websocket-stream/issues/139)
- [Does not properly handle backpressure](https://gist.github.com/lpinca/114a348f6108acc1e4236fed05522f73)
=> Add utility to wrap a `WebSocket` in a `Duplex` stream

README.md, doc/ws.md, examples/express-session-parse/index.js, examples/express-session-parse/public/app.js, examples/express-session-parse/public/index.html, lib/websocket-server.js
I submitted https://github.com/websockets/ws/pull/1612 to update `verifyClient` because I was unaware of https://github.com/websockets/ws/issues/377#issuecomment-462152231
This discussion has been going on since 2014 so I figured it would be useful to update some of the examples and docs to save someone else from making the mistake I did 😄 
This change:
- Updates the README with a client auth example
- Updates the existing express-sessions example to stop using `verifyClient`
- Put notes in the docs to discourage the use of `verifyClient`
=> docs: deprecate verifyClient

lib/buffer-util.js, test/buffer-util.test.js
_There are no known to me occurrences of returning uninitialized data, I am adding this as a safeguard._
---
This is just a safeguard that ensures that for cases if totalLength is by some mistake gets miscalculated, no uninitialized memory would be leaked.
This should not introduce any performance impact as in a normal case (which should be all the cases) this is just a single comparison.
=> Ensure that concat() never returns uninitialized data

lib/stream.js
closes https://github.com/websockets/ws/issues/1640
=> [minor] allow overriding default duplex stream options for createWebSocketStream

package.json
Listing packages mentioned in https://github.com/websockets/ws#opt-in-for-performance-and-spec-compliance as optional peer dependencies.
Additional context:
* [optional peer dependencies](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md) (implemented in `yarn@1.13.0`, `npm@6.11.0` but not [yet](https://github.com/nodejs/node/pull/29273) bundled with node and `pnpm@?`
I'm currently not using this feature myself until node bundles `npm@6.11`.  Just creating this PR now so that we can discuss any concerns you have.
=> fix: List optional peer dependencies

lib/validation.js, test/websocket.test.js
IANA has assigned 1014 as "Bad Gateway"
https://www.iana.org/assignments/websocket/websocket.xhtml#close-code-number
https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
ws support for 1012, and 1013 was added in b58f688bf0fa0e87a3cef87c2f5d01bf43590668
=> [fix] Allow close code 1014

bench/parser.benchmark.js, lib/receiver.js, lib/websocket.js, test/receiver.test.js, test/websocket-server.test.js, test/websocket.test.js
Follow the specification and close the connection when a non masked
frame is received on the server or a masked frame is received on the
client.
Refs: https://tools.ietf.org/html/rfc6455#section-5.1
Closes #1679
=> Close the connection if the MASK bit is incorrectly set

README.md
This was hanging node after tests when I included it in my application.
=> In the heartbeat example, stop the timer on close.

lib/stream.js, test/create-websocket-stream.test.js, test/permessage-deflate.test.js
Handle the breaking change introduced by https://github.com/nodejs/node/pull/29197.
=> Do not swallow errors emitted while destroying

lib/permessage-deflate.js, lib/sender.js, lib/websocket.js, test/permessage-deflate.test.js, test/websocket.test.js
If the socket is closed while data is being compressed, invoke the
current send callback and the buffered send callbacks with an error
before emitting the `'close'` event.
Refs: https://github.com/nodejs/node/pull/30596
=> Call buffered send callbacks on abnormal closure

lib/websocket.js, test/websocket.test.js
The WebSocket client [documentation](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) states that all [standard http.request()](https://nodejs.org/api/http.html#http_http_request_options_callback) options are valid.
> Any other option allowed in http.request() or https.request().
But if you create a new WebSocket client, the `auth` property in the options `object` parameter is ignored. And the `auth` property is a valid http.request() options
- version: all versions
1.  Create a Websocket client with an `auth` option:
```javascript
const auth = 'user:password';
const ws = new WebSocket('ws://localhost', {auth});
```
The server should receive the `auth` header. Eg: `Authorization: Basic dXNlcjpwYXNzd29yZA==`
No `auth` header is sent.
When the …
=> Honor auth option

README.md
1. The remind about 'authenticate' function implementing
2. Sending 401 HTTP response instead socket destroying
=> [doc] improve authentication example

lib/stream.js, test/create-websocket-stream.test.js
Handle the breaking change introduced by https://github.com/nodejs/node/pull/32780.
=> Call the `_final()` callback before destroying the stream

doc/ws.md, lib/event-target.js, test/websocket.test.js
As per the documentation this is something not browser related and should be supported to allow transparent polyfill usage
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
```js
import WebSocket from 'ws'
new WebSocket().addEventListener('message', () => {}, { once: true })
```
=> Add support for the EventTarget `once` option

doc/ws.md
clarify which of the mentioned http options can not be used in the WebSocket constructor but can be provided with the address parameter
=> update api doc to clarify WebSocket options

lib/permessage-deflate.js
Use `zlib.reset()` to (as per nodejs documentation `Reset the compressor/decompressor to factory defaults. Only applicable to the inflate and deflate algorithms.`)
Recently we have introduced/enabled `server_no_context_takeover` on one of our canary production servers which i monitor with nodejs with the help of this ws library (approx 250 connections on a single nodejs process connecting to the server).
With the introduction of `server_no_context_takeover` i have noticed significantly increased CPU usage on the client of approx 2x (8% -> 16%) to what it was before the parameter was added).
I have traced it down to significantly higher GC activity, which went from ~**100ms** total time/minute to ~**500ms**.
When it comes to actual GC counts, it went from ~**25 GC**/minute to ~**150**. …
=> reset compressor/decompressor instead of re-initialize

doc/ws.md
The type for `data` within the `send()` function is not `any`, but instead `<string> | <Buffer>`.
Try to say pass an object, and you'll be met with: 
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```
=> docs: Fixing `send` data type

lib/stream.js, lib/websocket.js, test/create-websocket-stream.test.js, test/websocket.test.js
Instead of destroying the socket, try to close the connection cleanly
if an error (such as a data framing error) occurs after the opening
handshake has completed.
Also, to comply with the specification, use the 1006 status code if no
close frame is received, even if the connection is closed due to an
error.
Fixes #1898
=> Close the connection cleanly when an error occurs

doc/ws.md, lib/permessage-deflate.js, lib/receiver.js, test/create-websocket-stream.test.js, test/receiver.test.js, test/websocket.test.js
Fixes #1892
~~This change doesn't change any messages or close codes, but does move the existing values into constants linked to the error code, to avoid repeating them at every point where the error is thrown.~~
=> Attach error codes to all receiver errors

lib/websocket.js, test/create-websocket-stream.test.js, test/websocket.test.js
Ensure that `socket.end()` is called if an error occurs simultaneously on
both peers.
Refs: https://github.com/websockets/ws/pull/1902
=> Fix close edge cases

lib/receiver.js, lib/sender.js, lib/stream.js, lib/websocket-server.js, lib/websocket.js
Refs: https://github.com/websockets/ws/pull/1910
=> Improve JSDoc-inferred types

doc/ws.md, lib/receiver.js, lib/websocket-server.js, lib/websocket.js, test/receiver.test.js
Add the `skipUTF8Validation` option to skip UTF-8 validation for text
and close messages.
Refs: https://github.com/websockets/ws/issues/1878
Closes #1924
=> Add ability to skip UTF-8 validation

index.js
Add `WebSocket.WebSocket` as an alias for `WebSocket` and
`WebSocket.WebSocketServer` as an alias for `WebSocket.Server` to fix
name consistency and improve interoperability with the ES module
wrapper.
Refs: https://github.com/websockets/ws/issues/1877
Refs: https://github.com/websockets/ws/issues/1932
=> Add `WebSocket.WebSocket{,Server}` aliases

README.md, doc/ws.md, lib/permessage-deflate.js, lib/sender.js, test/permessage-deflate.test.js, test/sender.test.js
When context takeover is enabled, compress messages even if their size
is below the value of `threshold` option.
Refs: https://github.com/websockets/ws/issues/1950
=> Ignore the `threshold` option if context takeover is enabled

lib/receiver.js, lib/sender.js
The ws library is using 32 bit values on the read and write for payload length.  This is because web sockets supports 63 bit payload lengths if the payload flag is 127 but JavaScript's max number is 53 bits - 1.
Node.js supports a 48 bit read and write operation.  The maximum payload length supported by 32 bits is 2.1gb.  The maximum payload length supported by 48 bits is 281tb.
Is there test automation or CI I can run this against?
=> extending ws to support 48bit values

lib/websocket.js, test/websocket.test.js
If the redirect URL is invalid, then emit the error instead of throwing
it, otherwise there is no way to handle it.
Closes #1975
=> Do not throw if the redirect URL is invalid

doc/ws.md, lib/receiver.js, lib/sender.js, lib/websocket.js, test/websocket.test.js
The `generateMask` option specifies a function that can be used to
generate custom masking keys.
Refs: https://github.com/websockets/ws/pull/1986
Refs: https://github.com/websockets/ws/pull/1988
Refs: https://github.com/websockets/ws/pull/1989
=>  Introduce the `generateMask` option

doc/ws.md
Prior to this commit, the documentation for the `verifyClient` option
was somewhat confusing due to its use of the passive voice and an
uncommon interpretation of the term "arguments."
Explain the way `ws` interprets the value of `verifyClient` using an
active voice and more traditional meanings of "parameters" and
"arguments."
=> [doc] Clarify interpretation of `verifyClient`

lib/permessage-deflate.js, lib/sender.js, test/sender.test.js
Do not convert strings to `Buffer`s if data does not need to be masked.
Refs: https://github.com/websockets/ws/pull/1998
=> Reduce buffer allocations

doc/ws.md, lib/websocket-server.js, test/websocket-server.test.js
@lpinca What do you think about adding this feature?
=> [WebSocketServer] Allow to extend the original `WebSocket` class

lib/websocket.js, test/websocket.test.js
Do not forward the `Authorization` and `Cookie` headers if the redirect
host is different from the original host.
=> Drop sensitive headers when following redirects

doc/ws.md
This documents the default values for `maxPayload`.
I got these by looking at the code here:
1. [WebSocket.Server](https://github.com/websockets/ws/blob/e1ddacce06d302884e674f50c12cb376e000c6ea/lib/websocket-server.js#L40)
2. [WebSocket client](https://github.com/websockets/ws/blob/6946f5fe781bafe99a36ed954904966203422b3d/lib/websocket.js#L622)
=> [doc] document defaults for maxPayload

doc/ws.md, lib/websocket.js, test/websocket.test.js
Add the ability to remove confidential headers on a per-redirect basis.
Closes #2014
=> Introduce the `'redirect'` event

doc/ws.md, lib/websocket-server.js, test/websocket-server.test.js
Add the ability to inspect the invalid handshake requests and respond
to them with a custom HTTP response.
Closes #2045
=> Introduce the `'wsClientError'` event

README.md, doc/ws.md, lib/buffer-util.js, lib/validation.js
When set to non empty values, the `WS_NO_BUFFER_UTIL` and
`WS_NO_UTF_8_VALIDATE` environment variables, prevent the optional
`bufferutil` and `utf-8-validate` dependencies  from being required,
respectively.
These might be useful to enhance security in systems where a user can
put a package in the package search path of an application of another
user, due to how the Node.js resolver algorithm works.
=> Add the `WS_NO_{BUFFER_UTIL, UTF_8_VALIDATE}` variables

doc/ws.md
This PR fixes a small typo where the link was not pointing to an anchor.
=> Fix typo in table of contents

doc/ws.md
websocket.send does not support a plain old Object of any shape and throws a TypeError.
This fixes the docs to remove Object as a supported type for the data parameter
Addresses #2076
=> In docs remove Object as a data type for send

doc/ws.md, lib/websocket.js, test/websocket-server.test.js, test/websocket.test.js
Document how to connect to a named pipe endpoint and the limitations.
Refs: https://github.com/websockets/ws/pull/1808
Refs: https://github.com/websockets/ws/pull/2075
=> Support Windows named pipes

test/create-websocket-stream.test.js
Fix a failure in test/create-websocket-stream.test.js if the node:domain module is loaded (e.g. due to NODE_OPTIONS in environment).
The cause of the failure was that installing an 'uncaughtException' event handler on process will cause node:domain to prepend its own handler for the same event, which confused the test.
Fixes: #2124
=> [fix] make test/create-websocket-stream.test.js compatible with domains

doc/ws.md, lib/websocket.js, test/websocket.test.js
This adds an option for WebSocket clients that makes it possible to add request headers late minute, specifically to support the use-case where a header can't be determined until the socket is connected (TLS channel binding), which means the `req.end()` call needs to be deferred.
I wasn't sure what the most elegant way to support this was so I've tried to keep this simple and minimally invasive, especially since it's for a rather obscure use-case. It just adds a callback hook which, if provided, will be invoked instead of `req.end()`. It's then up to the provided function call `req.end()` when it's done customizing the request.
If this interface looks okay I'll amend this pull request to document the option and add a test.
=> [feature] Add option to support late addition of headers

lib/receiver.js, test/receiver.test.js, test/websocket.test.js
To improve compatibility with the WHATWG standard, emit at most one of `'message'`, `'ping'`, and `'pong'` events per tick.
Fixes #2159
=> Emit at most one event per microtask

lib/websocket.js, test/websocket.test.js
Allow HTTP(S) URLs to be used in the WebSocket constructor. They are immediately converted to the ws and wss schemes.
Refs: https://github.com/whatwg/websockets/pull/45
=> Allow http and https schemes

lib/websocket.js, package.json, test/websocket-server.test.js
If you attempt to handle a websocket over a connection that is a stream but not a `net.Socket`, right now WS fails to do so. With this very small change (very similar to the [equivalent handling](https://github.com/nodejs/node/blob/fcf5de008a59229fe65a7b8e4e45fb4cfef4de81/lib/net.js#L2144-L2147) in Node itself) it's possible to call `handleUpgrade` with a socket argument that's actually just a duplex stream, and then successfully handle websocket traffic that way.
This can be useful in some cases: in my specific case this is required to proxy WebSockets over non-sockets, such as HTTP/2 streams (note that this is not the same as real WS-over-HTTP/2 support - I receive a proxy CONNECT sent on an HTTP/2 stream, and then the client does an HTTP/1.1 upgrade on that proxied stream, resulting in …
=> [fix] ensure handleUpgrade doesn't break if socket is just a stream

README.md
Since `isUtf8` is automatically present in modern versions of Node.js, we can cleanup this old info that doesn't apply anymore in order to simplify things and make the docs easier to read.
(It's also a footgun for people reading this passage and then installing both `bufferutil` and `utf-8-validate`.)
=> docs: clarify legacy deps

README.md, SECURITY.md, doc/ws.md
Added punctuation for readability.
=> [docs] Added punctuation for readability

doc/ws.md, lib/websocket.js, test/websocket.test.js
This adds support for a new `createConnection` option on client websockets, with the exact same functionality as the same option on `http.request` etc on Node.
The option is just passed straight through to `http(s).request`, so supports exactly the same functionality, including returning _any_ Duplex stream as a connection, not just net sockets.
This is useful in quite a few cases. In my specific case, I need to create an outgoing WebSocket over an existing duplex stream, and this makes that possible with `createConnection: () => stream`. I've tested this change in my codebase and it seems to be able to do that perfectly.
Notably though, this also makes it possible to potentially create WebSockets over things like HTTP/2 streams (see #1458). It probably doesn't fully provide that, and …
=> [feature] Add createConnection option to control client socket setup

lib/receiver.js, test/receiver.test.js, test/websocket.test.js
=> Emit at most one event per event loop iteration

doc/ws.md, lib/receiver.js, lib/websocket-server.js, lib/websocket.js, test/receiver.test.js
Flip the default value of the `allowSynchronousEvents` option to `true`.
Refs: https://github.com/websockets/ws/pull/2218
=> Flip the default value of `allowSynchronousEvents`

lib/websocket-server.js, lib/websocket.js, test/websocket-server.test.js, test/websocket.test.js
It is possible that the Upgrade header is correctly received and handled
(the `'upgrade'` event is emitted) without its value being returned to
the user. This can happen if the number of received headers exceed the
`server.maxHeadersCount` or `request.maxHeadersCount` threshold. In this
case `incomingMessage.headers.upgrade` may not be set.
Handle the case correctly and abort the handshake.
Fixes #2230
=> Fix crash when the Upgrade header cannot be read

doc/ws.md, lib/constants.js, lib/receiver.js, lib/sender.js, lib/validation.js, lib/websocket.js, test/receiver.test.js, test/sender.test.js, test/websocket.test.js
=> Add support for `Blob`

doc/ws.md
Follow the documentation specification and remove the useless `period`.
=> [doc] Remove useless period

lib/sender.js, lib/stream.js
This is an initial amount of work for improving the JSDocs in the codebase (as mentioned in #2241).
---
I figured it would make more sense to apply the JSDoc improvements incrementally. This has a few benefits:
- PRs end up being smaller to review (compared to if everything was done at once)
- Maintainers can more easily determine if #2241 is worth pursuing (in case they want to cancel everything or only accept fragments of the work)
- Contributors can make progress more asynchronously (in case there are gaps in free time)
Note: If the preference is only to merge everything at once, then this PR can be kept in a Draft State until it is "sufficiently complete".
When using JSDocs, TypeScript is fine with using `String` or `string`, `*` or `any`, and the like interchangeably. Not as …
=> Improve JSDoc Types (Part 1)

lib/permessage-deflate.js, test/permessage-deflate.test.js
This merge request fixes a long-standing issue in the handling of maxPayload violations during permessage-deflate decompression in the ws package.
Previously, when the payload exceeded the configured `maxPayload` size, the internal `zlib.InflateRaw` stream was reset via `.reset()` after removing the 'data' listener. However, this approach left unprocessed data in zlib's internal buffer queue. On large payloads (e.g., zip bombs that inflate to hundreds of megabytes), this residual data could be processed after the reset, causing zlib to throw a fatal error (`Z_DATA_ERROR`) due to missing dictionary state. note that the payload must be large enough so that zlib should fill its buffer and chunks in the buffer should have back-refrence to chunks before `.reset()`.
Replaced `this.reset()` with …
=> Fix zlib reset misuse on maxPayload error to prevent callback race and incorrect error code
