doc/ws.md

sync docs with code - https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L46

update WebSocket client docs

---

doc/ws.md

Add descriptions of permessage-deflate.

Documented permessage-deflate

---

README.md

I made ~50 PR before I found I can type `/releases` at the end of the URL.
bonus: Fixed typo.

add links, fix typo

---

doc/ws.md

fix typo in README

---

README.md

a simple expressjs example addressing a common use case

add express example

---

doc/ws.md
lib/WebSocket.js
test/WebSocket.test.js

Hi
I know this doesn't have major usage, but I found that there is no way to specify which network interface ws would use, during I've been trying to compare the responsibility of multiple networks. Am happy if you consider to merge this change. thanks!

Pass localAddress option to http request object.

---

lib/browser.js

fix for issue 603

---

README.md

ws module has no more support browserify bundle.

remove the browserify users section

---

lib/BufferUtil.fallback.js
lib/Receiver.js
lib/Validation.fallback.js

Buffer.concat(buffers) works fine.

Use Buffer.concat() instead of private concatBuffers method

---

lib/WebSocketServer.js

- Solution is to send headers before receiving the nonce

Fix for #687 Hixie-76 doesn't work behind HAProxy

---

lib/WebSocket.js
test/WebSocket.test.js

As discussed in https://github.com/websockets/ws/issues/553#issuecomment-136507574

Fixed error emission on receiver error

---

.gitignore
Makefile
package.json

Add make coverage command to get test coverage info

---

test/WebSocket.test.js

These changes are in anticipation of upcoming changes in node v7.0.0.
See: https://github.com/nodejs/node/pull/6102

test: update `should` usage

---

.eslintrc
Makefile
bench/parser.benchmark.js
bench/sender.benchmark.js
bench/speed.js
bench/util.js
lib/BufferPool.js
lib/BufferUtil.fallback.js
lib/ErrorCodes.js
lib/Extensions.js
lib/PerMessageDeflate.js
lib/Receiver.hixie.js
lib/Receiver.js
lib/Sender.hixie.js
lib/Sender.js
lib/Validation.fallback.js
lib/Validation.js
lib/WebSocket.js
lib/WebSocketServer.js

use strict mode

---

lib/WebSocket.js
lib/WebSocketServer.js
package.json

We just use a little options' feature, it can be implement with
ES6 feature now.

no more dependen on options

---

lib/PerMessageDeflate.js
lib/Receiver.js

This patch removes some unreachable branches and some unnecessary function calls.
See inline comments.

Remove some dead code

---

lib/WebSocketServer.js

Allow 'backlog' option for listening socket

---

bench/parser.benchmark.js
bench/speed.js
package.json

This cleans up the speed benchmark.

Clean up speed benchmark

---

doc/ws.md
lib/PerMessageDeflate.js
lib/Sender.js
test/Sender.test.js
test/WebSocket.test.js

I think we need an option like this to limit compression to larger payloads. The default value of 1024 bytes is taken from socket.io.

Add threshold option to compression.

---

lib/WebSocketServer.js

We are already using `ultron` on the client so I think it makes sense to also use it for the server.

Use ultron to handle the events listeners on the server

---

lib/WebSocketServer.js

This brings the following changes:
- Merge the `upgrade` function into `WebSocketServer.prototype.handleUpgrade()`.
- Extract `completeUpgrade` from `upgrade` and add it to `WebSocketServer.prototype`.

Move `completeUpgrade` to `WebSocketServer.prototype`

---

lib/WebSocketServer.js
test/WebSocketServer.test.js

This changes `WebSocketServer` to use the ES6 class syntax.

Refactor `WebSocketServer` to use class syntax

---

lib/Sender.js
lib/WebSocket.js

This patch removes some `try...catch` statements which seem to be redundant, see inline comments.

Remove unnecessary `try...catch` statements

---

README.md

Update coding style for README.md

---

package.json

Closes #1073
https://greenkeeper.io/

chore(package): update eslint-plugin-standard to version 3.0.0

---

test/WebSocket.test.js

This is the case for other platforms too.
I think this is the right way to do this, let me know if I got anything wrong!
cc/ @lpinca

[test] Skip test if 127.0.0.2 unavailable

---

lib/EventTarget.js
test/WebSocket.test.js

Set wasClean to true when close code is between 3000 and 4999

---

SECURITY.md

*Feel free to reject if these weren't your intentions* 
- Uses an unordered list for the vulnerability list to render each item on a new line.
- Fixes typo: vulnerablity -> vulnerability

Fix rendering of history in md file

---

doc/ws.md
lib/websocket.js
test/websocket.test.js

Addresses https://github.com/websockets/ws/issues/1143

[fix] Allow URL instances as URL for WebSocket constructors

---

lib/websocket.js
test/websocket.test.js

This fixes a regression introduced in 9e152f920a1818d8a23e0a113b4625c83f90d30d.

Add default value for `servername` option

---

bench/speed.js

I did some tests to see how ws performs over a unix socket.
Here are the changes I made to the benchmark tests

test: add unix sockets to bench

---

lib/receiver.js
test/receiver.test.js

Handle close frame which spans multiple packets

---

README.md

Remove new operator from https.createServer

Update HTTPS example, remove new createServer

---

lib/websocket-server.js

Replaced 'an' with 'a' in a couple of places.

Fixed a typo

---

README.md

https://github.com/websockets/ws/issues/1596

updated terminate() vs close() text in readme

---

lib/permessage-deflate.js

PerMessageDeflate#cleanup - properly cleanup on close

---

lib/websocket-server.js
test/websocket-server.test.js

Throw an error if `WebSocketServer.prototype.completeUpgrade()` is
called more than once with the same socket argument.

Throw an error on invalid method usage

---

lib/event-target.js
lib/limiter.js
lib/permessage-deflate.js
lib/receiver.js
lib/sender.js
lib/stream.js
lib/websocket-server.js
lib/websocket.js

Indicate optional params in JSDoc

---

lib/receiver.js

[fix] typo in receiver.js

---

doc/ws.md
lib/stream.js
lib/websocket.js
test/websocket.test.js

Add ability to pause and resume a websocket.

Add `WebSocket#pause()` and `WebSocket#resume()`

---

README.md

Updated example script for websocket server authentication README

Updated example script for websocket server README
